import type { GeneratorColors } from './generatorConfig'

export type PresetName = 'pink' | 'blue' | 'purple' | 'orange' | 'green' | 'black'

export const colorPresets: Record<PresetName, GeneratorColors> = {
  pink: {
    'listener-name': '#FFFFFF',
    'listener-name-bg': '#FB83AB',
    'member-name': '#FFFFFF',
    'member-name-bg': '#FB83AB',
    'listener-comment': '#333333',
    'listener-comment-bg': '#FFFFFF',
    'listener-comment-border': '#FB83AB',
    'member-comment': '#333333',
    'member-comment-bg': '#FFFFFF',
    'member-comment-border': '#FB83AB',
    'superchat-name': '#FFFFFF',
    'superchat-name-bg': '#FFAAC6',
    'superchat-comment': '#FFFFFF',
    'superchat-comment-bg': '#FB83AB',
    'membership-name': '#FFFFFF',
    'membership-name-bg': '#FFAAC6',
    'membership-comment': '#FFFFFF',
    'membership-comment-bg': '#FB83AB',
  },
  blue: {
    'listener-name': '#FFFFFF',
    'listener-name-bg': '#8CCCE3',
    'member-name': '#FFFFFF',
    'member-name-bg': '#8CCCE3',
    'listener-comment': '#333333',
    'listener-comment-bg': '#FFFFFF',
    'listener-comment-border': '#8CCCE3',
    'member-comment': '#333333',
    'member-comment-bg': '#FFFFFF',
    'member-comment-border': '#8CCCE3',
    'superchat-name': '#FFFFFF',
    'superchat-name-bg': '#9ED9EF',
    'superchat-comment': '#FFFFFF',
    'superchat-comment-bg': '#8CCCE3',
    'membership-name': '#FFFFFF',
    'membership-name-bg': '#9ED9EF',
    'membership-comment': '#FFFFFF',
    'membership-comment-bg': '#8CCCE3',
  },
  purple: {
    'listener-name': '#FFFFFF',
    'listener-name-bg': '#B77CEB',
    'member-name': '#FFFFFF',
    'member-name-bg': '#B77CEB',
    'listener-comment': '#333333',
    'listener-comment-bg': '#FFFFFF',
    'listener-comment-border': '#B77CEB',
    'member-comment': '#333333',
    'member-comment-bg': '#FFFFFF',
    'member-comment-border': '#B77CEB',
    'superchat-name': '#FFFFFF',
    'superchat-name-bg': '#C891F8',
    'superchat-comment': '#FFFFFF',
    'superchat-comment-bg': '#B77CEB',
    'membership-name': '#FFFFFF',
    'membership-name-bg': '#C891F8',
    'membership-comment': '#FFFFFF',
    'membership-comment-bg': '#B77CEB',
  },
  orange: {
    'listener-name': '#FFFFFF',
    'listener-name-bg': '#FDA25F',
    'member-name': '#FFFFFF',
    'member-name-bg': '#FDA25F',
    'listener-comment': '#333333',
    'listener-comment-bg': '#FFFFFF',
    'listener-comment-border': '#FDA25F',
    'member-comment': '#333333',
    'member-comment-bg': '#FFFFFF',
    'member-comment-border': '#FDA25F',
    'superchat-name': '#FFFFFF',
    'superchat-name-bg': '#FFBB88',
    'superchat-comment': '#FFFFFF',
    'superchat-comment-bg': '#FDA25F',
    'membership-name': '#FFFFFF',
    'membership-name-bg': '#FFBB88',
    'membership-comment': '#FFFFFF',
    'membership-comment-bg': '#FDA25F',
  },
  green: {
    'listener-name': '#FFFFFF',
    'listener-name-bg': '#7AC970',
    'member-name': '#FFFFFF',
    'member-name-bg': '#7AC970',
    'listener-comment': '#333333',
    'listener-comment-bg': '#FFFFFF',
    'listener-comment-border': '#7AC970',
    'member-comment': '#333333',
    'member-comment-bg': '#FFFFFF',
    'member-comment-border': '#7AC970',
    'superchat-name': '#FFFFFF',
    'superchat-name-bg': '#90D387',
    'superchat-comment': '#FFFFFF',
    'superchat-comment-bg': '#7AC970',
    'membership-name': '#FFFFFF',
    'membership-name-bg': '#90D387',
    'membership-comment': '#FFFFFF',
    'membership-comment-bg': '#7AC970',
  },
  black: {
    'listener-name': '#FFFFFF',
    'listener-name-bg': '#8D8D8D',
    'member-name': '#FFFFFF',
    'member-name-bg': '#8D8D8D',
    'listener-comment': '#333333',
    'listener-comment-bg': '#FFFFFF',
    'listener-comment-border': '#8D8D8D',
    'member-comment': '#333333',
    'member-comment-bg': '#FFFFFF',
    'member-comment-border': '#8D8D8D',
    'superchat-name': '#FFFFFF',
    'superchat-name-bg': '#8D8D8D',
    'superchat-comment': '#FFFFFF',
    'superchat-comment-bg': '#717171',
    'membership-name': '#FFFFFF',
    'membership-name-bg': '#8D8D8D',
    'membership-comment': '#FFFFFF',
    'membership-comment-bg': '#717171',
  },
}
